site_name: Cloudneeti Documentation
site_description: Cloudneeti Documentation
site_author: The Cloudneeti Team
repo_name: Cloudneeti_SaaS_Docs
copyright: "&copy; 2019 Cloudneeti."

theme:
  name: 'material'
  custom_dir: "theme"
  static_templates:
      - index.html
  feature:
    tabs: true
  palette:
    primary: 'cloudneeti'
    accent: 'cloudneeti'
  logo:
    icon: 'cloud'
  font:
    text: 'Helvetica'
    code: 'Helvetica Mono'
  logo: 'images/logo_top.png'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/custom.js'
  
nav:
- Getting Started: 
  - CLOUDNEETI PRODUCT: 
    - Product Overview: gettingStarted/productOverview.md
    - Product Capabilities: gettingStarted/productCapabilities.md
    - Cloud Accounts​: gettingStarted/cloudAccounts.md
    - Licenses: gettingStarted/licenses.md
    - User & Roles : gettingStarted/userRoles.md
  - USER IDENTITY MANAGEMENT:
    - Authentication: gettingStarted/authentication.md
    - Authorization: gettingStarted/authorization.md
  - ACTIVATE LICENSE: gettingStarted/howToActivateLicense​.md
- Administrator Guide:
  - ONBOARDING CLOUD ACCOUNTS:
    - Azure Subscriptions: administratorGuide/azureSubscriptions.md
    - Amazon Web Service Accounts: administratorGuide/amazonWebServiceAccounts.md
    - Office 365 Subscriptions: administratorGuide/office365Subscriptions.md
  - MANAGE CLOUD ACCOUNTS:
    - Add Cloud Account: administratorGuide/addCloudAccount.md
    - Configure Security Policies: administratorGuide/configureSecurityPolicies.md
    - Configure Notifications: administratorGuide/configureNotifications.md
    - Configure Data Collection: administratorGuide/configureDataCollection.md
    - Manage Cloud Account Users (goes to CAU): administratorGuide/manageCloudAccountUsers.md
  - MANAGE USERS:
    - License Users: administratorGuide/licenseUsers.md
    - Cloud Account Users (CAU page): administratorGuide/cloudAccountUsers.md
  - MANAGE REMEDIATIONS:
    - For Azure Policies: administratorGuide/forAzurePolicies.md
    - For AWS Policies: administratorGuide/forAWSPolicies.md
  - MANAGE INTEGRATIONS:
    - INCIDENT MANAGEMENT (TICKETING):
      - Service Now: administratorGuide/serviceNow.md
      - Zen Desk: administratorGuide/zenDesk.md
    - REPORTING DATA FEEDS:
      - Bring your blob storage: administratorGuide/bringYourBlobStorage.md
      - Bring your NoSQL storage: administratorGuide/bringYourNoSQLStorage.md
  - MANAGE ORGANIZATION:
    - Manage Licenses: administratorGuide/manageLicenses.md
- User Guide:
  - DASHBOARDS: 
    - CISO: userGuide/CISO.md
    - SOC​: userGuide/SOC​.md
    - Assets: userGuide/assets.md
  - SECURITY POLICIES:
    - Categories and Policies​ Details (Description, Resources, Audit procedure, Remediation guidance)​: userGuide/categoriesAndPolicies.md
  - RISK POSTURE:
    - Risk Dashboard: userGuide/riskDashboard.md
    - Risk Analysis & Prioritization: userGuide/riskAnalysis&Prioritization.md
  - REPORTS:
    - Download and Understand reports: userGuide/downloadAndUnderstandReports.md
    