site_name: Documentation
site_description: Cloudneeti Documentation
site_author: The Cloudneeti Team
repo_name: Cloudneeti_SaaS_Docs
copyright: "&copy; 2019 Cloudneeti."

google_analytics: ['UA-149855644-1', 'docs.cloudneeti.com']

theme:
  name: 'material'
  custom_dir: "theme"
  static_templates:
      - index.html
  feature:
    tabs: false
  palette:
    primary: 'cloudneeti'
    accent: 'cloudneeti'
  logo:
    icon: 'cloud'
  font:
    text: 'Poppins'
    # code: 'Helvetica Mono'
  logo: 'images/logo.png'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/custom.js'
  
nav:
- Introduction: 
  - Getting Started: gettingStarted/introduction.md
  - Product Features: gettingStarted/productFeatures.md
  - Deployment Architecture: gettingStarted/deploymentArchitecture.md
  - Customer Data Security: gettingStarted/customerDataSecurity.md
  - Glossary: gettingStarted/glossary.md
- Try and Buy:
  - Free Trial: azureMarketplace/freeTrial.md
  - Buy on Azure Marketplace: azureMarketplace/subscribeOnAzureMarketplace.md
  - Request a License: gettingStarted/subscribe.md
  - Estimate Pricing: azureMarketplace/estimatePricing.md
- Onboarding Guide:
   - Overview: onboardingGuide/onboardingGuideOverview.md
   - Micorsoft Azure: onboardingGuide/azureSubscriptions.md
   - Amazon Web Services: onboardingGuide/amazonWebServiceAccounts.md
   - Office 365: onboardingGuide/office365Subscription.md
- User Guide:
  - Sign In and Sign Out: gettingStarted/signInAndSignOut.md
  - User Interface: userGuide/userInterface.md
  - Dashboards: userGuide/dashboards.md
  - Security Policies: userGuide/securityPolicies.md
  - Compliance Benchmarks: userGuide/complianceBenchmarks.md
  - Reports: userGuide/reports.md
- Administrator Guide:
  - Features and Quotas: administratorGuide/featuresAndQuotas.md
  - Integrations: administratorGuide/manageLicenses.md
  - Cloud Accounts: administratorGuide/manageAccounts.md
  - Users & Roles: administratorGuide/manageUsers.md
  - Security Policy Configuration: administratorGuide/securityPolicyExclusions.md
  - Audit Log: administratorGuide/auditLog.md
- Remediation:
  - Overview: remediation/overview.md
  - Azure:
    - Guided: remediation/azureGuidedRemediation.md
    - Quick Wins: remediation/azureQuickWins.md
    - Auto Remediation: remediation/azureAutoRemediation.md
    - Decommission of remediation: remediation/azureDecommissionofRemediation.md
  - AWS: remediation/awsRemediation.md
- Release Notes:
  - Releases in 2019: releaseNotes/releaseNotes.md
# - Parent:
#     - Child 1:
#         - Child 2: 'releaseNotes/releaseNotes.md'
#         - Child 3: 'releaseNotes/releaseNotes.md'