site_name: Documentation
site_description: Cloudneeti Documentation
site_author: The Cloudneeti Team
repo_name: Cloudneeti_SaaS_Docs
copyright: "&copy; 2020 Cloudneeti."

google_analytics: ['UA-149855644-1', 'docs.cloudneeti.com']

theme:
  name: 'material'
  custom_dir: "theme"
  static_templates:
      - index.html
  feature:
    tabs: false
  palette:
    primary: 'cloudneeti'
    accent: 'cloudneeti'
  logo:
    icon: 'cloud'
  font:
    text: 'Poppins'
    # code: 'Helvetica Mono'
  logo: 'images/logo.png'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/custom.js'
extra_templates:
  - 'releaseNotes/currentVersion.html'
markdown_extensions:
    - attr_list

nav:
- Introduction: 
  - Getting Started: gettingStarted/introduction.md
  - Product Features: gettingStarted/productFeatures.md
  - Cloud Security Best Practices : gettingStarted/cloudSecurityBestPractices.md
  - Deployment Architecture: gettingStarted/deploymentArchitecture.md
  - Customer Data Security: gettingStarted/customerDataSecurity.md
  - Glossary: gettingStarted/glossary.md
- Try and Buy:
  - Free Trial: tryAndBuy/freeTrial.md
  - Buy on Azure Marketplace: tryAndBuy/subscribeOnAzureMarketplace.md
  - Request a License: tryAndBuy/subscribe.md
  - Partner co-branding: tryAndBuy/partnerCobranding.md
  - Estimate Pricing: tryAndBuy/estimatePricing.md
- Onboarding Guide:
  - Overview: onboardingGuide/onboardingGuideOverview.md
  - Amazon Web Services: 
    - Onboarding steps: onboardingGuide/amazonWebServiceAccounts.md
    - OS baseline (optional): onboardingGuide/awsVMBaselineConfiguration.md
    - Configure quick wins: onboardingGuide/awsQuickWins.md
  - Micorsoft Azure:
    - Onboarding steps: onboardingGuide/azureSubscriptions.md
    - Additional roles: onboardingGuide/grantAccessToAzureSubscriptionAdditionalRoles.md
    - Key vaults: onboardingGuide/grantAccessToKeyVaults.md
    - Advanced security configurations: onboardingGuide/azureAdvancedSecurityConfiguration.md
    - Quick wins: onboardingGuide/azureQuickWins.md
    - OS baseline and vulnerability: onboardingGuide/azureVulnerability.md
    - Kubernetes cluster: onboardingGuide/configureCloudneetiAgentInKubernetesCluster.md
  - Office 365: 
    - Onboarding steps: onboardingGuide/office365Subscription.md
    - Upgrade advanced security configurations: onboardingGuide/office365AdvanceSecurityConfigurationUpgrade.md
- User Guide:
  - Sign In and Sign Out: gettingStarted/signInAndSignOut.md
  - User Interface: userGuide/userInterface.md
  - Dashboards: userGuide/dashboards.md
  - Security Policies: userGuide/securityPolicies.md
  - Compliance Benchmarks: userGuide/complianceBenchmarks.md
  - Reports: userGuide/reports.md
  - Cloudneeti REST APIs: 
    - Rest APIs: userGuide/restAPIs.md
    - API User Scenarios: userGuide/apiUserScenarios.md
    - Token API: userGuide/tokenAPI.md
    - Onboard cloud account API: userGuide/onboardCloudAccount.md
    - Update API app access scope API: userGuide/updateAPIAppAccessScope.md
    - Initiate scan API: userGuide/initiateScanAPI.md
    - Scan status API: userGuide/scanStatusAPI.md
    - Audit report API: userGuide/auditReportAPI.md
- Administrator Guide:
  - Features and Quotas: administratorGuide/featuresAndQuotas.md
  - Integrations: administratorGuide/manageLicenses.md
  - ASC Integration: administratorGuide/azureASCPushIntegration.md
  - Cloud Accounts: administratorGuide/manageAccounts.md
  - Users & Roles: administratorGuide/manageUsers.md
  - Private Benchmark: administratorGuide/privateBenchmark.md
  - Security Policy Configuration: administratorGuide/securityPolicyExclusions.md
  - Audit Log: administratorGuide/auditLog.md
  - Configure Cloudneeti API Access: administratorGuide/configureCloudneetiAPIAccess.md
- Remediation:
  - Overview: remediation/overview.md
  - Azure:
    - Guided Remediation: remediation/azureGuidedRemediation.md
    - Quick Wins: remediation/azureQuickWins.md
    - Auto Remediation: remediation/azureAutoRemediation.md
    - Decommission of remediation: remediation/azureDecommissionofRemediation.md
  - AWS:
    - Guided Remediation: remediation/awsGuidedRemediation.md
    - Auto Remediation: remediation/awsRemediation.md
    - Decommission Remediation framework: remediation/awsDecommissionofRemediation.md
- Release Notes:
  - Releases in 2020: releaseNotes/2020.md
  - Releases in 2019: releaseNotes/2019.md
# - Parent:
#     - Child 1:
#         - Child 2: 'releaseNotes/releaseNotes.md'
#         - Child 3: 'releaseNotes/releaseNotes.md'