site_name: Cloudneeti Documentation
site_description: Cloudneeti Documentation
site_author: The Cloudneeti Team
repo_name: Cloudneeti_SaaS_Docs
copyright: "&copy; 2019 Cloudneeti."

theme:
  name: 'material'
  custom_dir: "theme"
  static_templates:
      - index.html
  feature:
    tabs: false
  palette:
    primary: 'cloudneeti'
    accent: 'cloudneeti'
  logo:
    icon: 'cloud'
  font:
    text: 'Poppins'
    # code: 'Helvetica Mono'
  logo: 'images/logo.png'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/custom.js'
  
nav:
- Getting Started: 
  - Introduction: gettingStarted/introduction.md
  - Subscribe: gettingStarted/subscribe.md
  - System Architecture: gettingStarted/systemArchitecture.md
  - Sign In and Sign Out: gettingStarted/signInAndSignOut.md
- Try and Buy:
  - Azure Marketplace: azureMarketplace/Subscribe_on_Azure_Marketplace.md
- Onboarding Guide:
   - Overview: onboardingGuide/onboardingGuideOverview.md
   - Azure Subscriptions: onboardingGuide/azureSubscriptions.md
   - AWS Accounts: onboardingGuide/amazonWebServiceAccounts.md
   - Office 365 Subscriptions: onboardingGuide/onboardingOffice365Subscription.md
- User Guide:
  - UI Navigation: userGuide/userGuideUINavigation.md
  - Dashboards: userGuide/dashboards.md
  - Security Policies: userGuide/securityPolicies.md
  - Compliance Benchmarks: userGuide/complianceBenchmarks.md
  - Reports: userGuide/reports.md
- Administrator Guide:
  - Manage Accounts: administratorGuide/manageAccounts.md
  - Manage Licenses: administratorGuide/manageLicenses.md
  - Manage Users: administratorGuide/manageUsers.md
  - Audit Log: administratorGuide/auditLog.md
- Cloudneeti Remediation:
  - Overview: cloudneetiRemediation/overview.md
  - Azure Subscription: cloudneetiRemediation/azureSubscriptionRemediation.md
- Release Notes:
  - Releases in 2019: releaseNotes/releaseNotes.md